### ISSUE TITLE
Preprocessor directives are incorrectly evaluated in generated code

### ISSUE THREAD

**Issue by ltrzesniewski** [JetBrains/ForTea#15]
I don't know if that's an issue in Rider (2019.3 EAP 6) or if it's caused by ForTea, but I noticed something really strange.

If you use T4 to generate a C# file which contains a `#if` directive, the condition is not evaluated correctly by the IDE:

![image](https://user-images.githubusercontent.com/7913492/69544384-e716ea00-0f8f-11ea-95dc-035af506ef2d.png)

This example is from a .NET Standard 2.0 project, and it correctly generates an error at compilation.

The same piece of code in a different file (not generated by T4) is evaluated correctly:

![image](https://user-images.githubusercontent.com/7913492/69544728-9d7acf00-0f90-11ea-8fe6-7c1461fe06fd.png)

It looks like the IDE thinks no symbols are defined, but just for files generated by T4. Something like `#if true` will be included by the IDE:

![image](https://user-images.githubusercontent.com/7913492/69544618-61476e80-0f90-11ea-92fa-01249626a985.png)

**Comment by kirillgla** [comment]
Thank you for your report!
I fixed that. The fix has been pushed to net193 and will be available in the next EAP
