### ISSUE TITLE
Partials are not seen by the T4 editor

### ISSUE THREAD

**Issue by ltrzesniewski** [JetBrains/ForTea#16]
In Rider 2019.3 EAP 6, if you write a `TextTemplatingFilePreprocessor` template, the T4 file editor doesn't seem to know about template parts defined in other files (using `partial`).

For example, with the following `TestTemplate.tt` file:

```
<#@ template language="C#" #>
<#= SomeValue #>
```

And the following C# code besides it:

```C#
partial class TestTemplate
{
    public int SomeValue { get; set; }
}
```

The editor doesn't know about the `SomeValue` property:

![image](https://user-images.githubusercontent.com/7913492/69641147-f49ba500-105f-11ea-93eb-1116425ec484.png)

Even though the template compiles fine.

**Comment by kirillgla** [comment]
I fixed that in a branch. The fix will be not available in 2019.3 but will arrive in `2019.3 bugfix`
