### ISSUE TITLE
Build yourself?

### ISSUE THREAD

**Issue by KCarterSr** [JetBrains/ForTea#18]
Do we really have to build this our self's?
Can't this just be a normal plugin that we install via Resharper just like all the rest?

Thanks

**Comment by kirillgla** [comment]
Yes, you are right, we'll publish the plugin into ReSharper Plugin Gallery some time soon

**Comment by KCarterSr** [comment]
Thank you

**Comment by axunonb** [comment]
Here's an updated PR https://github.com/jpeirson/ForTea/pull/1 based on the jpeirson original modifications, which includes a NuGet package as version 1.15.0, which can be installed for ReSharper 2019.2.3

**Comment by benblo** [comment]
I can't install it :( ! I followed the instructions here: https://resharper-support.jetbrains.com/hc/en-us/articles/207241675-Offline-plug-in-installation-process
... the last staff comment says it won't list plugins that aren't compatible with the R# version, but I unzipped the nupkg (I did remove the extra .zip) and I can't find anything in there that specifies version compatibility...

**Comment by benblo** [comment]
Installation instructions: https://resharper-support.jetbrains.com/hc/en-us/articles/207241675-Offline-plug-in-installation-process
Be sure to remove the extra .zip extension.

**Comment by kirillgla** [comment]
Thank you for the effort! The changes in the PR you suggested have already been done in this repository. The plugin source code is already compatible with recent versions of R#

**Comment by axunonb** [comment]
> 
> 
> Thank you for the effort! The changes in the PR you suggested have already been done in this repository. The plugin source code is already compatible with recent versions of R#

Frankly, I built the package because I needed it urgently, and it was before I became aware Jetrains have taken over. So it was just about sharing a ready-to-use solution. Appreciate the new repo.

**Comment by kirillgla** [comment]
FYI, [the plugin for ReSharper 2019.3-eap07](https://plugins.jetbrains.com/plugin/13469-fortea/) has just been published

**Comment by kirillgla** [comment]
[The plugin for ReSharper 2019.3](https://plugins.jetbrains.com/plugin/13469-fortea/) has been published. So now it is no longer necessary to build it yourself

**Comment by TimSirmovics** [comment]
I can't find the plug in the extension manager for 2013.3 using feed https://resharper-plugins.jetbrains.com/api/v2/curated-feeds/Wave_v193.0/

**Comment by kirillgla** [comment]
Well, that's strange. Has it appeared now?

**Comment by TimSirmovics** [comment]
Yes it is there now!
