### ISSUE TITLE
Assemblies referenced through MSBuild property cause fatal error

### ISSUE THREAD

**Issue by ltrzesniewski** [JetBrains/ForTea#19]
Sorry, I fully expect you to hate me and my crazy T4 files by now, so here's another issue 😄 

Basically, I followed the guidance in [the T4 docs](https://docs.microsoft.com/en-us/visualstudio/modeling/t4-assembly-directive?view=vs-2019) and wrote something like this in the project:

```XML
<ItemGroup>
  <!-- The GeneratePathProperty metadata will make NuGet generate a PkgFody property -->
  <!-- See https://github.com/NuGet/NuGet.Client/pull/2271 -->
  <!-- $(FodyVersion) comes from Directory.Build.props -->
  <PackageReference Include="Fody" Version="$(FodyVersion)" GeneratePathProperty="true" />
</ItemGroup>

<PropertyGroup>
  <!-- This is the property read by VS and supplied to T4 -->
  <MonoCecilPath>$(PkgFody)\netclassictask\Mono.Cecil.dll</MonoCecilPath>
</PropertyGroup>

<ItemGroup>
  <!-- This is not necessary for the IDE, it's used only when invoking T4 from MSBuild -->
  <T4ParameterValues Include="MonoCecilPath" Value="$(MonoCecilPath)" Visible="false" />
</ItemGroup>
```

And the following directive in the T4 file:

```
<#@ assembly name="$(MonoCecilPath)" #>
```

I got this result when trying to execute the template:

![image](https://user-images.githubusercontent.com/7913492/70277101-fc6eee00-17b1-11ea-8ef9-c0325fde8835.png)

Also, the syntax highlighting and contextual actions don't seem very stable - they get turned off as soon as I edit the T4 file.

This happens with the IL.Emit.tt file in following commit: https://github.com/ltrzesniewski/InlineIL.Fody/commit/cf535c06a3ca7ce17acbd57b5465e862d64df4e8

Tested with Rider 2019.3 EAP 7. This time I made sure it works fine in VS on a different PC.

**Comment by kirillgla** [comment]
Oh, your crazy T4 files are OK, I am really thankful to you for sharing that! It's strange that this doesn't work. I'll investigate that. Meanwhile, I expect a small exclamation mark to appear in the bottom-right corner of the IDE after a fatal error. Could you report that error to JetBrains, please?
![image](https://user-images.githubusercontent.com/31822295/70378840-3bc64780-1936-11ea-9a77-5fd4d8ee4f4a.png)

**Comment by ltrzesniewski** [comment]
Sure, I just submitted DEXP-495699

**Comment by ltrzesniewski** [comment]
Sure, I just submitted the following:

- DEXP-495699
- DEXP-495700
- DEXP-495701
- DEXP-495702
- DEXP-495703

I also had these existing issues show up:

- DEXP-488949
- DEXP-491644

**Comment by kirillgla** [comment]
Thank you very much!

**Comment by kirillgla** [comment]
Ok, I fixed this one, too. The file you mentioned now contains no red code and compiles and executes without errors. The fix will (hopefully) be publicly available soon. [Here](https://github.com/JetBrains/ForTea/files/4416939/ForTea-2020.1.9999.zip)'s a build that includes this fix (as well as a fix for https://github.com/JetBrains/ForTea/issues/19) in case you want to have it right away. As always, any feedback is welcome. Thank you! 😄

**Comment by ltrzesniewski** [comment]
That's great, thanks a lot! 😄

**Comment by ltrzesniewski** [comment]
I can confirm this one works great in 2020.1 EAP 7 (with the build you provided here). Thanks! 😄
