### ISSUE TITLE
Types generated by T4 are not always visible in multi-targeted projects

### ISSUE THREAD

**Issue by ltrzesniewski** [JetBrains/ForTea#20]
Here's another one 😄 

When a class is generated by T4, it's not detected in all target frameworks of other projects when they are multi-targeted.

Maybe it's simpler to explain with an example:

- `NetStdLib/NetStdLib.csproj`:

```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <None Update="TestTemplate.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>TestTemplate.cs</LastGenOutput>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <Compile Update="TestTemplate.cs">
      <DependentUpon>TestTemplate.tt</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
```

- `NetStdLib/TestTemplate.tt`:

```
<#@ template language="C#" #>
namespace NetStdLib
{
    public class ClassDefinedByTemplate
    {
    }
}
```

- `NetStdLib/TestTemplate.cs`: (generated file)

```C#
namespace NetStdLib
{
    public class ClassDefinedByTemplate
    {
    }
}
```

- `MultiTfmLib/MultiTfmLib.csproj`:

```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;netcoreapp3.0</TargetFrameworks>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\NetStdLib\NetStdLib.csproj" />
  </ItemGroup>
</Project>
```

- `MultiTfmLib/TestClass.cs`:

```C#
using NetStdLib;

namespace MultiTfmLib
{
    public class TestClass
    {
        public static void Test()
        {
            _ = new ClassDefinedByTemplate();
        }
    }
}
```

The code in `TestClass` is seen differently in Rider when displayed for the two different projects:

- `netcoreapp3.0`:

![image](https://user-images.githubusercontent.com/7913492/70627148-f9e31d00-1c25-11ea-8515-664328951311.png)

Everything works fine here.

- `net48`:

![image](https://user-images.githubusercontent.com/7913492/70627204-12533780-1c26-11ea-80ef-f71de29fd829.png)

The IDE does not recognize `ClassDefinedByTemplate`. This code compiles correctly though.

Tested with Rider 2019.3 EAP 7.

Repro solution: [RiderT4.zip](https://github.com/JetBrains/ForTea/files/3950660/RiderT4.zip)

**Comment by ltrzesniewski** [comment]
As an aside, this issue, along with #15, seems to show that C# files generated by T4 are handled _differently_ than regular C# files by Rider. Is there a reason for this?

I suppose other issues could be present because of this different handling. Couldn't you just make Rider handle the generated C# files the same way as normal files?

**Comment by ltrzesniewski** [comment]
Well, this looks like it's _almost_ fixed in 2019.3 Final. Thanks! 😄 

In that version, there's still a weirdness when you remove the `_ = new ClassDefinedByTemplate();` line:

- `netcoreapp3.0`:

![image](https://user-images.githubusercontent.com/7913492/70637583-c27d6c00-1c37-11ea-858c-1d37e6d984f5.png)

- `net48`:

![image](https://user-images.githubusercontent.com/7913492/70637627-d2954b80-1c37-11ea-83bf-f9a72c4f0de9.png)

You need to restart Rider after removing the `_ = new ClassDefinedByTemplate();` line.

Anyway this downgraded from "major annoyance" to "minor edge case" now in 2019.3 Final. I'm keeping this open in case you'd like to fix it. 😄

**Comment by kirillgla** [comment]
Thank you for the report! I'll investigate that once I have the time. 😄
> C# files generated by T4 are handled _differently_ than regular C# files by Rider. Is there a reason for this?

You're totally right, the generated code _used to_ be handled differently in earlier versions for performance reasons. We later decided, however, that it was not worth it.

**Comment by ltrzesniewski** [comment]
Actually, it seems the issue is still there is 2019.3 Final, but *not* on a multi-targeted project this time. I'll try to reproduce the problem in a clean solution later, but I just wanted to give you a heads-up.

**Comment by ltrzesniewski** [comment]
Here's an updated repro, tested with 2020.1 EAP 6:

[RiderT4.zip](https://github.com/JetBrains/ForTea/files/4408110/RiderT4.zip)

It fails in the IDE on the `net48` target, but compiles fine:

![image](https://user-images.githubusercontent.com/7913492/78012394-2e99f200-7345-11ea-938e-cb15b055d4d8.png)

Unloading then reloading `NetStdLib` fixes the issue, but you'll get the same problem when you close and reopen the solution.

Something similar is happening in our real solutions, and most of my team disabled ForTea because of that - it messes up the IDE all over the place. 😢

**Comment by kirillgla** [comment]
Thank you very much for the updated repro project!

**Comment by kirillgla** [comment]
Ok, I think I figured out why the plugin behaved like that and found a solution.
![image](https://user-images.githubusercontent.com/31822295/78167256-d94e0580-7456-11ea-9ed3-4b9f45a8f77c.png)
I hope the fix will be publicly available somewhere between 2020.1 EAP 7 and 2020.1 release.
[Here](https://github.com/JetBrains/ForTea/files/4416678/ForTea-2020.1.9999.zip) is a build of the plugin that includes the fix in case you want to have it right away. Any feedback on whether or not it worked out for you is very welcome. 😄
Thank you very much for your help!

**Comment by ltrzesniewski** [comment]
Thanks a lot! I'll test that version tomorrow and let you know.

**Comment by ltrzesniewski** [comment]
Well, I'm not sure if I did something wrong, but I tested both builds you provided (here and in #19), and they don't seem to fix either issue... I used the "Install plugin from disk" action.

I got this error (DEXP-509773):

```
Message = “Can not find assembly name info in project NetStdLib for target framework .NETFramework,Version=v4.8.”
ExceptionPath = Root.InnerException.InnerException.InnerException
ClassName = System.Exception
HResult = COR_E_EXCEPTION=80131500
Source = JetBrains.Platform.ProjectModel
StackTraceString = “
  at JetBrains.ProjectModel.ProjectExtensions.GetOutputAssemblyNameInfo(IProject project, TargetFrameworkId targetFrameworkId)
     at JetBrains.ReSharper.Daemon.CSharp.Stages.UnreferencedModuleDetector..ctor(IPsiModule psiModule)
     at JetBrains.ReSharper.Daemon.Asp.CSharp.Stages.AspUnreferencedModuleDetectorFactory.CreateDetectUnreferencedModule(IPsiSourceFile sourceFile)
     at JetBrains.ReSharper.Daemon.CSharp.Stages.CSharpErrorStage.CreateProcess(IDaemonProcess process, IContextBoundSettingsStore settings, DaemonProcessKind processKind, ICSharpFile file)
     at JetBrains.ReSharper.Feature.Services.CSharp.Daemon.CSharpDaemonStageBase.<>c__DisplayClass1_0.<CreateProcess>b__0(IFile file)
     at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
     at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at JetBrains.Util.CollectionUtil.AsArray[T](IEnumerable`1 enumerable)
     at JetBrains.ReSharper.Feature.Services.Daemon.DaemonProcessBase.RunStage(IDaemonStage stage, DaemonProcessKind processKind, Action`2 commiter, IContextBoundSettingsStore contextBoundSettingsStore, JetHashSet`1 disabledStages)
     at JetBrains.ReSharper.Feature.Services.Daemon.DaemonProcessBase.<>c__DisplayClass47_1.<DoHighlighting>g__Stage|2(IDaemonStage stage)
     at JetBrains.Application.Threading.Tasks.TaskBarrier.<>c__DisplayClass22_1.<EnqueueDependentJobs>b__2()
     at JetBrains.Application.Threading.Tasks.TaskHost.AccessViolationCatcher(Action action)
     at JetBrains.Application.Threading.Tasks.TaskHost.<>c__DisplayClass36_0.<Create>b__1(Object state)
     at System.Threading.Tasks.Task.Execute()
”
```

I thought your build may be conflicting with the bundled one, so I also tried uninstalling the build you provided (to remove it from `%LOCALAPPDATA%\JetBrains\Toolbox\apps\Rider\ch-0\201.6487.145.plugins`, then replacing the bundled `%LOCALAPPDATA%\JetBrains\Toolbox\apps\Rider\ch-0\201.6487.145\plugins\ForTea` with it (basically `201.6487.145.plugins` instead of `201.6487.145\plugins`). It didn't help 😞.

**Comment by kirillgla** [comment]
Ok, that's strange. Thank you very much for testing, I'll double-check that

**Comment by kirillgla** [comment]
Yes, indeed, simply installing the new version of the plugin doesn't change much. Invalidating caches and restarting, however, did the trick for me. Does it work for you, too?

**Comment by kirillgla** [comment]
The T4 files still cannot be executed, but at least the IDE stops being messed up. The exception you've just shown indeed kills syntax highlighting and execution of templates. It originates in the Rider itself, not in the plugin, so I'm afraid there isn't much I can do about it. It has already been fixed, though, so I believe these templates will work fine in some future EAP or release. 😄

**Comment by ltrzesniewski** [comment]
I already tried invalidating the caches and restarting before I've sent that previous message, and it didn't fix the issue in my real solution (I mean the IDE was still messed up).

But I may have done that with the first binary you posted but not the second one, I don't remember. I'll try it once more on the repro and the real solution with the second binary after replacing the bundled one, and I'll tell you how it goes. I'll do it a bit later though (right now I have 4 large solutions open that I don't want to close just yet).

If you've tested the plugin on a newer build of Rider that may indeed explain why it works for you, but it's good news 😄

**Comment by ltrzesniewski** [comment]
After making sure the caches were invalidated and using your build from [here](https://github.com/JetBrains/ForTea/issues/19#issuecomment-607417879), the small repro works fine, but my real solution is still messed up, unfortunately. 😢 

I'm getting the same exception in `GetOutputAssemblyNameInfo` (which was expected), plus some others which don't seem related (some assertion failures in `CSharpCompilerNullableInspector` and a `Wrong thread null` on the Java side from what seems to be the Rider protocol).

I guess I'll need to find a better repro, but maybe I should wait for the next EAP?

**Comment by kirillgla** [comment]
Thank you very much for testing that! 😄
Now EAP 7 has arrived. Yes, a better repro would help a lot.
Btw if your real solution is OSS, I could have a look at the real solution itself instead.

**Comment by ltrzesniewski** [comment]
Thanks, but unfortunately I can't give you access to my real solution.

I'll test the last build again with EAP 7, and I'll try to come up with another repro if it still fails.

**Comment by kirillgla** [comment]
Ok. Looking forward to seeing the new repro. Thank you very much!

**Comment by ltrzesniewski** [comment]
Good news: it seems to work fine on EAP 7 with the ForTea build from #19! 🎉 

I just made a quick test though, without _really_ working on the solution. I'll close this in a few days if I see no issue. Thanks again! 😄
