### ISSUE TITLE
HostSpecific=true breaks templates in subfolders

### ISSUE THREAD

**Issue by pietervp** [JetBrains/ForTea#22]
Maybe this is a local problem. For me, it's very easy to reproduce:

Rider Build: #RD-193.5662.14

Repro project:
[ClassLibrary1.zip](https://github.com/JetBrains/ForTea/files/4004793/ClassLibrary1.zip)

hostspecific = false => no problem
hostspecific = true  => error message

Error message upon executing the template inside a subfolder:
`
DocumentModel.tt(17, 30): [CS0234] The type or namespace name 'TextTransformation' does not exist in the namespace 'ClassLibrary1' (are you missing an assembly reference?)
`

**Comment by amoerie** [comment]
We're also seeing this problem.. Is there any way to make T4 templates work both in VS and in Rider?

**Comment by kirillgla** [comment]
Thank you for the report! This issue [has been fixed](https://youtrack.jetbrains.com/issue/RIDER-37599) and will be available in Rider starting around version 2020.1 EAP3
