### ISSUE TITLE
Value tuples are not supported in templates

### ISSUE THREAD

**Issue by ltrzesniewski** [JetBrains/ForTea#23]
If you try to use a value tuple in template code, the generator will fail to build the template:

>   TestTemplate.tt(3, 9): [CS8356] Predefined type 'System.ValueTuple`3' is declared in multiple referenced assemblies: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

Example template:

```
<#@ template language="C#" #>
<#
    _ = (1, 2, 3);
#>
```

This template executes fine with VS, but fails in Rider 2019.3.1.

**Comment by kirillgla** [comment]
Thank you for the report! Sorry for the very late reply, I didn't get the notification about this issue for some reason. We did indeed have some issues with referencing assemblies, they're fixed now.
![image](https://user-images.githubusercontent.com/31822295/78028141-3074ad00-7367-11ea-8fb3-38ce4f5cd066.png)
