### ISSUE TITLE
The tab key does not indent template text

### ISSUE THREAD

**Issue by ltrzesniewski** [JetBrains/ForTea#29]
If you select a few lines of text _outside_ of `<#`...`#>` regions and press tab, the selected text gets replaced with a tab instead of being indented. Shift+Tab unindents the text as expected.

The tab key works as expected inside `<#`...`#>` blocks.

**Comment by ltrzesniewski** [comment]
This may be related to https://youtrack.jetbrains.com/issue/RSRP-474524

**Comment by kirillgla** [comment]
Thank you. The problem you reported is indeed a duplicate of [that one](https://youtrack.jetbrains.com/issue/RSRP-474524). Feel free to follow it for updates 😄
