### ISSUE TITLE
Preprocessed templates always generate public classes

### ISSUE THREAD

**Issue by ltrzesniewski** [JetBrains/ForTea#35]
The following template:

```
<#@ template language="C#" visibility="internal" #>
```

Will generate a `public` class instead of an `internal` one after using the _Preprocess Template_ action.

Visual Studio generates an `internal` template class, as well as an `internal` base class.

Tested with v2020.2.33, shipped with Rider 2020.2 EAP 2.

**Comment by kirillgla** [comment]
The fix will be available in the next 2020.3 EAP. Thank you!
