### ISSUE TITLE
Text Template Utility Methods marked as errors

### ISSUE THREAD

**Issue by aybe** [JetBrains/ForTea#36]
Hello,

The text template utility methods are not recognized by R# even though they are indeed correct:

![devenv_2020-09-14_03-17-26](https://user-images.githubusercontent.com/1537591/93033983-d461c480-f638-11ea-931c-7797b7a59224.png)

https://docs.microsoft.com/en-us/visualstudio/modeling/text-template-utility-methods?view=vs-2019

Thanks !

**Comment by benblo** [comment]
I've had that as well, clearing the R# solution cache fixed it.

**Comment by aybe** [comment]
Great, thanks.
