### ISSUE TITLE
Availability for Visual Studio 2022 Current with ReSharper 2021.3?

### ISSUE THREAD

**Issue by JonathanLydall** [JetBrains/ForTea#61]
I currently have 2021.3 EAP 7 installed, but this extension isn't showing as an ReSharper extension.

What's the plan with support for Visual Studio 2022 Current and ReSharper 2021.3?

**Comment by kirillgla** [comment]
The extension is not available for EAP versions of ReSharper. I recommend rolling back to the current latest release version of it (2021.2.2) or waiting for the release of 2021.3. Please, let me know if it's broken after that. Thanks!

**Comment by pmatrosov** [comment]
Resharper 2021.3 is out. But extension is still unavailable, isn't showing at extensions list.
VS 2019 (16.11.7)
